config/routes.rb
SchedulePebbleCard::Application.routes.draw do
  resources :schedules

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :gameday, :location, :opponent, :time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all

    respond_to do |format|
      format.html # index.html.erb
      source = 'https://my.clemson.edu/srv/feed/static/athletics/football/schedule.json'
      resp = Net::HTTP.get_response(URI.parse(source))
      data = resp.body
      result = JSON.parse(data)
      i = 0
      count = 0
      output=""


      while i < result["data"]["schedule"].count and count < 4 do
        if Date.parse(result["data"]["schedule"][i]["date"]) > DateTime.now.to_date
          if result["data"]["schedule"][i]["location"] != "Memorial Stadium" and result["data"]["schedule"][i]["location"] != "Clemson, SC"
            output=output+"@"+result["data"]["schedule"][i]["title"]+" "+Date.parse(result["data"]["schedule"][i]["date"]).strftime("%-m/%d")+ "\n"
            count +=1
          else
            output=output+result["data"]["schedule"][i]["title"]+" "+Date.parse(result["data"]["schedule"][i]["date"]).strftime("%-m/%d")+ "\n"
            count +=1
          end
        end
        i +=1
      end
      output = {:content => output}.to_json
      format.json { render json: output.gsub(/\([^)]+\)\s+/,'')}
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(params[:schedule])

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render json: @schedule, status: :created, location: @schedule }
      else
        format.html { render action: "new" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SchedulePebbleCard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gameday %><br />
    <%= f.date_select :gameday %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :opponent %><br />
    <%= f.text_field :opponent %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>

<table>
  <tr>
    <th>Gameday</th>
    <th>Time</th>
    <th>Opponent</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schedules.each do |schedule| %>
  <tr>
    <td><%= schedule.gameday %></td>
    <td><%= schedule.time %></td>
    <td><%= schedule.opponent %></td>
    <td><%= schedule.location %></td>
    <td><%= link_to 'Show', schedule %></td>
    <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
    <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Gameday:</b>
  <%= @schedule.gameday %>
</p>

<p>
  <b>Time:</b>
  <%= @schedule.time %>
</p>

<p>
  <b>Opponent:</b>
  <%= @schedule.opponent %>
</p>

<p>
  <b>Location:</b>
  <%= @schedule.location %>
</p>


<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>